<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>schema</string>
	</array>
	<key>name</key>
	<string>SpatialOS Schema</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#package</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(type)\s+([\w]+)\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>type definition</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.type</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(component)\s+([\w]+)\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>component definition</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.component</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>command</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.data</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.data</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>command declaration</string>
			<key>match</key>
			<string>(command)\s+(\w+)\s+(\w+)\s+(returns)\s+(\w+)\;</string>
			<key>name</key>
			<string>meta.component.body</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>comment</key>
			<string>a schema comment</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<key>field</key>
		<dict>
			<key>comment</key>
			<string>field definition</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\s+(\w+)\s+(\=)\s+(\d+)\;</string>
					<key>name</key>
					<string>meta.type.field</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(map)\&lt;(\w+)(\,)\s*(\w+)\&gt;\s+(\w+)\s+(\=)\s+(\d+)\;</string>
					<key>name</key>
					<string>meta.type.field</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(option)\&lt;(\w+)\&gt;\s+(\w+)\s+(\=)\s+(\d+)\;</string>
					<key>name</key>
					<string>meta.type.field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive</string>
				</dict>
			</array>
		</dict>
		<key>id</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>id declaration</string>
			<key>match</key>
			<string>(id)\s*(\=)\s*(\d+)\;</string>
			<key>name</key>
			<string>meta.component.body</string>
		</dict>
		<key>import</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.import</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>import company.package;</string>
			<key>match</key>
			<string>(import)\s+("[\w\/]+[a-zA-Z0-9_]+\.schema")(;)</string>
			<key>name</key>
			<string>meta.import</string>
		</dict>
		<key>package</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.package</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.package</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>package company.package;</string>
			<key>match</key>
			<string>(package)\s+([\w\.]+)(;)</string>
			<key>name</key>
			<string>meta.package</string>
		</dict>
		<key>primitive</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.primitive</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>built in data type</string>
			<key>match</key>
			<string>\b(bool|uint32|uint64|int32|int64|sint32|sint64|fixed32|fixed64|sfixed32|sfixed64|float|double|string|bytes|Coordinates|Vector3d|Vector3f|EntityId|EntityPosition|option|map)\b</string>
			<key>name</key>
			<string>meta.declaration.body</string>
		</dict>
		<key>storage</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.data</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>data declaration</string>
			<key>match</key>
			<string>(data)\s+(\w+)\;</string>
			<key>name</key>
			<string>meta.component.body</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.schema</string>
	<key>uuid</key>
	<string>8751c4b8-ddba-49e9-bc2b-692b27305ffc</string>
</dict>
</plist>
